# Imagem base com Node.js
FROM node:20

# Diretório de trabalho dentro do container
WORKDIR /usr/src/app

# Copia todos os arquivos da máquina host para o container
COPY . .

# Comando padrão (pode ser sobrescrito no docker-compose)
CMD ["node", "Exercícios/1.js"]
